site_name: Seminar SS 2020 Comp.Phil.Hist.Science
nav:
  - Projekte:
      Aztec Butterflies:
        Text: aztec_classification_of_butterflies/FlorentineCodexButterflies.md
        Notebook: aztec_classification_of_butterflies/TheButterfliesOfTheFlorentineCodex.ipynb
      NYC benches:
        Text: citybenches_nyc/city_benches_nyc.md
        Notebook1: citybenches_nyc/01dataimport.ipynb
        Notebook2: citybenches_nyc/02geocoding.ipynb
        Notebook3: citybenches_nyc/03distancecalc.ipynb
        Notebook4: citybenches_nyc/04shortestdist.ipynb
        Notebook5: citybenches_nyc/05presentation.ipynb
      Nurse Hate Thread:
        Text: nurse_hate_thread/Zwischenbericht.md
        Notebook: nurse_hate_thread/NurseHate.ipynb
      Project Disagreement:
        Text: project_disagreement/hcq_expressing_disagreement_in_abstracts.md
        Notebook: project_disagreement/disagreement_abstracts.ipynb
      Water Security:
        Text: water_security/text.md
        Notebook1: water_security/Comparison_water_(in)security_based_on_noun_chunks.ipynb
        Notebook2: water_security/Notebook-Spacy.ipynb
theme:
  name: readthedocs
  font: Roboto
  language: en
  highlightjs: true
  hljs_languages:
     - python
     - yaml
  palette:
    primary: teal
    accent: "deep orange"
extra_css:
    - 'stylesheets/extra.css'
markdown_extensions:
  - footnotes
plugins:
  - search
  - mkdocstrings
  - bibtex:
      bib_file:  "seminar.bib"
      cite_style:  "pandoc"
      csl_file: "chicago.csl"
  - mkdocs-jupyter:
      include_source: True

